version: "3.9"

services:
  mysql:
    container_name: symfony_mysql
    image: mysql:8.0
    command: [ '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci', '--default-authentication-plugin=mysql_native_password' ]
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER-symfony}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - data-mysql:/var/lib/mysql
    ports:
      - ${MYSQL_PORT}:3306
    networks:
      - symfony_app

  php-fpm:
    container_name: symfony_php_fpm
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    restart: on-failure
    volumes:
      - ./application/:/var/www/app
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ~/.composer/docker-cache/:/root/.composer
    depends_on:
      - mysql
    networks:
      - symfony_app

  nginx:
    container_name: symfony_nginx
    image: nginx:1.17.7-alpine
    restart: on-failure
    volumes:
      - ./application/:/var/www/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - ${NGINX_PORT}:80
    depends_on:
      - php-fpm
    networks:
      - symfony_app

volumes:
  data-mysql:
    name: symfony_mysql

networks:
  symfony_app:
    name: symfony_app